/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'publishDate' : Time,
  'description' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'projectType' : string,
  'name' : string,
  'deadline' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
  'budget' : string,
}
export interface PortfolioItem {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'description' : string,
  'category' : string,
}
export interface Stats {
  'yearsOfExperience' : bigint,
  'clientCount' : bigint,
  'expertCount' : bigint,
  'projectCount' : bigint,
}
export interface TeamMember {
  'id' : bigint,
  'linkedin' : string,
  'twitter' : string,
  'instagram' : string,
  'name' : string,
  'role' : string,
  'photoUrl' : string,
}
export interface Testimonial {
  'id' : bigint,
  'review' : string,
  'starRating' : bigint,
  'clientName' : string,
  'photoUrl' : string,
  'company' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addBlogPost' : ActorMethod<[string, string, string], bigint>,
  'addPortfolioItem' : ActorMethod<[string, string, string, string], bigint>,
  'addTeamMember' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addTestimonial' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllPortfolioItems' : ActorMethod<[], Array<PortfolioItem>>,
  'getAllTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getPortfolioItemsByCategory' : ActorMethod<[string], Array<PortfolioItem>>,
  'getStats' : ActorMethod<[], Stats>,
  'seedData' : ActorMethod<[], undefined>,
  'submitContact' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'updateStats' : ActorMethod<[bigint, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];