/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'publishDate' : Time,
  'description' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'projectType' : IDL.Text,
  'name' : IDL.Text,
  'deadline' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
  'budget' : IDL.Text,
});
export const PortfolioItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'id' : IDL.Nat,
  'linkedin' : IDL.Text,
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'photoUrl' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'review' : IDL.Text,
  'starRating' : IDL.Nat,
  'clientName' : IDL.Text,
  'photoUrl' : IDL.Text,
  'company' : IDL.Text,
});
export const Stats = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'clientCount' : IDL.Nat,
  'expertCount' : IDL.Nat,
  'projectCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPortfolioItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTeamMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
  'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getPortfolioItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PortfolioItem)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'seedData' : IDL.Func([], [], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'publishDate' : Time,
    'description' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'projectType' : IDL.Text,
    'name' : IDL.Text,
    'deadline' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
    'budget' : IDL.Text,
  });
  const PortfolioItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'id' : IDL.Nat,
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'photoUrl' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'review' : IDL.Text,
    'starRating' : IDL.Nat,
    'clientName' : IDL.Text,
    'photoUrl' : IDL.Text,
    'company' : IDL.Text,
  });
  const Stats = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'clientCount' : IDL.Nat,
    'expertCount' : IDL.Nat,
    'projectCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPortfolioItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTeamMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllPortfolioItems' : IDL.Func([], [IDL.Vec(PortfolioItem)], ['query']),
    'getAllTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getPortfolioItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PortfolioItem)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'seedData' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateStats' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };